apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-app
spec:
  selector:
    matchLabels:
      app: mediawiki-app
  replicas: 1           # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mediawiki-app
    spec:
      containers:
      - name: mediawiki-container
        image: mediawiki
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/images
          name: mediawiki-volume
        - mountPath: /var/www/html/LocalSettings.php
          name: mediawiki-localsettings
      volumes:
      - name: mediawiki-volume
      - name: mediawiki-localsettings
        hostPath:
          path: /home/ubuntu/mediawiki/LocalSettings.php
          type: File
---

apiVersion: v1
kind: Service
metadata:
  name: mediawiki-srv
  labels:
    app: mediawiki-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: mediawiki-app
