apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-db
spec:
  selector:
    matchLabels:
      app: mediawiki-db
  replicas: 1       # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mediawiki-db
    spec:
      containers:
      - name: mediawiki-db-container
        image: mariadb
        env:
        - name: MYSQL_DATABASE
          value: my_wiki
        - name: MYSQL_USER
          value: wikiuser
        - name: MYSQL_PASSWORD
          value: example
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: 'yes'
---

apiVersion: v1
kind: Service
metadata:
  name: mediawiki-db-srv
  labels:
    app: mediawiki-db
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mediawiki-db
